name: GitHub Actions Demo
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Push to ecs
        run: printenv &&  chmod +x deploy.sh && RUNNER_ALLOW_RUNASROOT="1"  ./deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION  }}
