name: GitHub Actions Demo
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Push to ecs
      env:
        aws_access_key_id : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
      run: printenv &&  chmod +x deploy.sh && RUNNER_ALLOW_RUNASROOT="1"  sudo ./deploy.sh
